name: ringo
description: Japanese MorphologicalAnalysis
version: 0.0.1
homepage: https://kawa.dev

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: ringoPlugin
  assets:
    - packages/ringo/assets/base.csv
    - packages/ringo/assets/check.csv
