name: ringo
description: Morphological analysis of Japanese sentences. This Flutter plugin helps you to analyze Japanese sentences.
version: 0.0.1
homepage: https://kawa.dev
repository: https://github.com/kawa1214/ringo

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/ringo/assets/base.csv
    - packages/ringo/assets/check.csv
