name: reviewdog
on: [pull_request]
jobs:
  dartanalyzer:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@main
        with:
          fetch-depth: 1
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: x64
      - name: Run dartanalyzer
        uses: HansChua/dartanalyzer-reviewdog-action@main
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review 