name: flutter_analyze_and_test

on:
  pull_request:
    types: [opened, synchronize]
  push:

jobs:
  test:
    name: flutter reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: dartcop . | reviewdog -f=checkstyle -name=dartcop -reporter=github-pr-review
      - run: flutter analyze
      - run: flutter test --verbose --coverage --coverage-path=~/coverage/lcov.info
